name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set vars
      id: set-vars
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
        echo "build_time=$(date +'%Y%m%d-%s')" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node_modules-${{hashFiles('package-lock.json')}}
        restore-keys: node_modules-

    - name: Install dependencies
      run: |
        npm install

    - name: Zip and Upload to S3
      env:
        AWS_REGION: us-east-1
        S3_BUCKET: digitax-admin
        APP_VERSION: app-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip
      run: |
        zip -r $APP_VERSION * .[^.]*
        aws s3 cp $APP_VERSION s3://$S3_BUCKET/$APP_VERSION

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_REGION: us-east-1
        APPLICATION_NAME: Digitax-admin
        APP_VERSION: app-${{ steps.set-vars.outputs.short_sha }}-${{ steps.set-vars.outputs.build_time }}.zip
        ENVIRONMENT_NAME: Digitax-admin-env
        S3_BUCKET: digitax-admin
      run: |
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $APP_VERSION --source-bundle S3Bucket=$S3_BUCKET,S3Key=$APP_VERSION
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $APP_VERSION